// <auto-generated />
using System;
using ForQab.DataAccess.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForQab.Migrations.MyDb
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20241202065715_ManytoMany")]
    partial class ManytoMany
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetUserRoles_RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            //modelBuilder.Entity("ExpertSubProfession", b =>
            //    {
            //        b.Property<int>("ExpertId")
            //            .HasColumnType("int");

            //        b.Property<int>("SubProfessionId")
            //            .HasColumnType("int");

            //        b.HasKey("ExpertId", "SubProfessionId");

            //        b.HasIndex("SubProfessionId");

            //        b.ToTable("ExpertSubProfession");
            //    });

            modelBuilder.Entity("ForQab.Models.AspNetRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedName" }, "RoleNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedName] IS NOT NULL)");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ForQab.Models.AspNetRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "RoleId" }, "IX_AspNetRoleClaims_RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("ForQab.Models.AspNetUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<string>("LastName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "NormalizedEmail" }, "EmailIndex");

                    b.HasIndex(new[] { "NormalizedUserName" }, "UserNameIndex")
                        .IsUnique()
                        .HasFilter("([NormalizedUserName] IS NOT NULL)");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ForQab.Models.AspNetUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserClaims_UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("ForQab.Models.AspNetUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex(new[] { "UserId" }, "IX_AspNetUserLogins_UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("ForQab.Models.AspNetUserToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ForQab.Models.Commission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommissionNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("commission_no");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.HasKey("Id")
                        .HasName("PK__commissi__3213E83F3B4ABE27");

                    b.HasIndex("SectionId");

                    b.ToTable("commissions");
                });

            modelBuilder.Entity("ForQab.Models.DimRepresentative", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("PK__dim_repr__3213E83F4D403BCE");

                    b.ToTable("dim_representative");
                });

            modelBuilder.Entity("ForQab.Models.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("RegionId")
                        .HasColumnType("int")
                        .HasColumnName("region_id");

                    b.HasKey("Id")
                        .HasName("PK__district__3213E83F8DDCBF8C");

                    b.HasIndex("RegionId");

                    b.ToTable("districts");
                });

            modelBuilder.Entity("ForQab.Models.ExamBuilding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.HasKey("Id")
                        .HasName("PK__exam_bui__3213E83FF7187075");

                    b.HasIndex("SectionId");

                    b.ToTable("exam_building");
                });

            modelBuilder.Entity("ForQab.Models.Expert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("PK__experts__3213E83FCCBE8A03");

                    b.HasIndex("SectionId");

                    b.ToTable("experts");
                });

            modelBuilder.Entity("ForQab.Models.Gender", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__genders__3213E83FC52E1E40");

                    b.ToTable("genders");
                });

            modelBuilder.Entity("ForQab.Models.Monitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<byte>("Archive")
                        .HasColumnType("tinyint")
                        .HasColumnName("archive");

                    b.Property<int?>("District")
                        .HasColumnType("int")
                        .HasColumnName("district");

                    b.Property<string>("FinCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("fin_code");

                    b.Property<string>("Fname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fname");

                    b.Property<int?>("Foto")
                        .HasColumnType("int")
                        .HasColumnName("foto");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("position");

                    b.Property<string>("Profession")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("profession");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("region");

                    b.Property<byte?>("Role")
                        .HasColumnType("tinyint")
                        .HasColumnName("role");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<string>("Serial")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("serial");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("surname");

                    b.Property<string>("TelEv")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("tel_ev");

                    b.Property<string>("TelIs")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)")
                        .HasColumnName("tel_is");

                    b.Property<int?>("VNum")
                        .HasColumnType("int")
                        .HasColumnName("v_num");

                    b.Property<string>("Workplace")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("workplace");

                    b.HasKey("Id")
                        .HasName("PK__supervis__3213E83FAB6F6A67");

                    b.HasIndex("District");

                    b.HasIndex("Gender");

                    b.HasIndex("Role");

                    b.HasIndex("SectionId");

                    b.ToTable("monitors");
                });

            modelBuilder.Entity("ForQab.Models.MonitorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Note")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("note");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int")
                        .HasColumnName("supervisor_id");

                    b.HasKey("Id")
                        .HasName("PK__supervis__3213E83F0BEE1DF8");

                    b.HasIndex("SupervisorId");

                    b.ToTable("monitor_logs");
                });

            modelBuilder.Entity("ForQab.Models.Profession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.HasKey("Id")
                        .HasName("PK__professi__3213E83FCA289D09");

                    b.HasIndex("SectionId");

                    b.ToTable("professions");
                });

            modelBuilder.Entity("ForQab.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__regions__3213E83F8E8C9763");

                    b.ToTable("regions");
                });

            modelBuilder.Entity("ForQab.Models.Role", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__roles__3213E83F4B5228FB");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("ForQab.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__sections__3213E83F295BA8C8");

                    b.ToTable("sections");
                });

            modelBuilder.Entity("ForQab.Models.SubCommission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommissionId")
                        .HasColumnType("int")
                        .HasColumnName("commission_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<string>("SubCommissionNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("sub_commission_no");

                    b.HasKey("Id")
                        .HasName("PK__sub_comm__3213E83FFB765CF8");

                    b.HasIndex("CommissionId");

                    b.HasIndex("SectionId");

                    b.ToTable("sub_commissions");
                });

            modelBuilder.Entity("ForQab.Models.SubProfession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int")
                        .HasColumnName("profession_id");

                    b.Property<int>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.HasKey("Id")
                        .HasName("PK__sub_prof__3213E83F14C802DD");

                    b.HasIndex("ProfessionId");

                    b.HasIndex("SectionId");

                    b.ToTable("sub_professions");
                });

            modelBuilder.Entity("ForQab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short?>("Gender")
                        .HasColumnType("smallint")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int")
                        .HasColumnName("section_id");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("surname");

                    b.HasKey("Id")
                        .HasName("PK__Users__3213E83FD3D6EAF2");

                    b.HasIndex("SectionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AspNetUserRole", b =>
                {
                    b.HasOne("ForQab.Models.AspNetRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ForQab.Models.AspNetUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            //modelBuilder.Entity("ExpertSubProfession", b =>
            //    {
            //        b.HasOne("ForQab.Models.Expert", null)
            //            .WithMany()
            //            .HasForeignKey("ExpertId")
            //            .OnDelete(DeleteBehavior.Cascade)
            //            .IsRequired();

            //        b.HasOne("ForQab.Models.SubProfession", null)
            //            .WithMany()
            //            .HasForeignKey("SubProfessionId")
            //            .OnDelete(DeleteBehavior.Cascade)
            //            .IsRequired();
            //    });

            modelBuilder.Entity("ForQab.Models.AspNetRoleClaim", b =>
                {
                    b.HasOne("ForQab.Models.AspNetRole", "Role")
                        .WithMany("AspNetRoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ForQab.Models.AspNetUserClaim", b =>
                {
                    b.HasOne("ForQab.Models.AspNetUser", "User")
                        .WithMany("AspNetUserClaims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForQab.Models.AspNetUserLogin", b =>
                {
                    b.HasOne("ForQab.Models.AspNetUser", "User")
                        .WithMany("AspNetUserLogins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForQab.Models.AspNetUserToken", b =>
                {
                    b.HasOne("ForQab.Models.AspNetUser", "User")
                        .WithMany("AspNetUserTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ForQab.Models.Commission", b =>
                {
                    b.HasOne("ForQab.Models.Section", "Section")
                        .WithMany("Commissions")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK__commissio__secti__5441852A");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ForQab.Models.District", b =>
                {
                    b.HasOne("ForQab.Models.Region", "Region")
                        .WithMany("Districts")
                        .HasForeignKey("RegionId")
                        .IsRequired()
                        .HasConstraintName("FK__districts__regio__0E6E26BF");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("ForQab.Models.ExamBuilding", b =>
                {
                    b.HasOne("ForQab.Models.Section", "Section")
                        .WithMany("ExamBuildings")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK__exam_buil__secti__5165187F");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ForQab.Models.Expert", b =>
                {
                    b.HasOne("ForQab.Models.Section", "Section")
                        .WithMany("Experts")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_Experts_Sections");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ForQab.Models.Monitor", b =>
                {
                    b.HasOne("ForQab.Models.District", "DistrictNavigation")
                        .WithMany("Monitors")
                        .HasForeignKey("District")
                        .HasConstraintName("FK__monitor_district");

                    b.HasOne("ForQab.Models.Gender", "GenderNavigation")
                        .WithMany("Monitors")
                        .HasForeignKey("Gender")
                        .HasConstraintName("FK__monitor_genders");

                    b.HasOne("ForQab.Models.Role", "RoleNavigation")
                        .WithMany("Monitors")
                        .HasForeignKey("Role")
                        .HasConstraintName("FK__monitor_role");

                    b.HasOne("ForQab.Models.Section", "Section")
                        .WithMany("Monitors")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK__superviso__secti__60A75C0F");

                    b.Navigation("DistrictNavigation");

                    b.Navigation("GenderNavigation");

                    b.Navigation("RoleNavigation");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ForQab.Models.MonitorLog", b =>
                {
                    b.HasOne("ForQab.Models.Monitor", "Supervisor")
                        .WithMany("MonitorLogs")
                        .HasForeignKey("SupervisorId")
                        .IsRequired()
                        .HasConstraintName("FK__superviso__super__6B24EA82");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("ForQab.Models.Profession", b =>
                {
                    b.HasOne("ForQab.Models.Section", "Section")
                        .WithMany("Professions")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK_Professions_Sections");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ForQab.Models.SubCommission", b =>
                {
                    b.HasOne("ForQab.Models.Commission", "Commission")
                        .WithMany("SubCommissions")
                        .HasForeignKey("CommissionId")
                        .IsRequired()
                        .HasConstraintName("FK__sub_commi__commi__5812160E");

                    b.HasOne("ForQab.Models.Section", "Section")
                        .WithMany("SubCommissions")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK__sub_commi__secti__571DF1D5");

                    b.Navigation("Commission");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ForQab.Models.SubProfession", b =>
                {
                    b.HasOne("ForQab.Models.Profession", "Profession")
                        .WithMany("SubProfessions")
                        .HasForeignKey("ProfessionId")
                        .IsRequired()
                        .HasConstraintName("FK_Professions_Sub_Professions");

                    b.HasOne("ForQab.Models.Section", "Section")
                        .WithMany("SubProfessions")
                        .HasForeignKey("SectionId")
                        .IsRequired()
                        .HasConstraintName("FK_Sub_Professions_Sections");

                    b.Navigation("Profession");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ForQab.Models.User", b =>
                {
                    b.HasOne("ForQab.Models.Section", "Section")
                        .WithMany("Users")
                        .HasForeignKey("SectionId")
                        .HasConstraintName("FK_Users_Sections");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("ForQab.Models.AspNetRole", b =>
                {
                    b.Navigation("AspNetRoleClaims");
                });

            modelBuilder.Entity("ForQab.Models.AspNetUser", b =>
                {
                    b.Navigation("AspNetUserClaims");

                    b.Navigation("AspNetUserLogins");

                    b.Navigation("AspNetUserTokens");
                });

            modelBuilder.Entity("ForQab.Models.Commission", b =>
                {
                    b.Navigation("SubCommissions");
                });

            modelBuilder.Entity("ForQab.Models.District", b =>
                {
                    b.Navigation("Monitors");
                });

            modelBuilder.Entity("ForQab.Models.Gender", b =>
                {
                    b.Navigation("Monitors");
                });

            modelBuilder.Entity("ForQab.Models.Monitor", b =>
                {
                    b.Navigation("MonitorLogs");
                });

            modelBuilder.Entity("ForQab.Models.Profession", b =>
                {
                    b.Navigation("SubProfessions");
                });

            modelBuilder.Entity("ForQab.Models.Region", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("ForQab.Models.Role", b =>
                {
                    b.Navigation("Monitors");
                });

            modelBuilder.Entity("ForQab.Models.Section", b =>
                {
                    b.Navigation("Commissions");

                    b.Navigation("ExamBuildings");

                    b.Navigation("Experts");

                    b.Navigation("Monitors");

                    b.Navigation("Professions");

                    b.Navigation("SubCommissions");

                    b.Navigation("SubProfessions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
