//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMASServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AMASServiceReference.GetPhotoFromIAMASSoap")]
    public interface GetPhotoFromIAMASSoap
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhotoFromIAMAS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AMASServiceReference.GetPhotoFromIAMASResponse> GetPhotoFromIAMASAsync(AMASServiceReference.GetPhotoFromIAMASRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhotoFromIAMAS24", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AMASServiceReference.GetPhotoFromIAMAS24Response> GetPhotoFromIAMAS24Async(AMASServiceReference.GetPhotoFromIAMAS24Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPhotoFromCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AMASServiceReference.GetPhotoFromCardResponse> GetPhotoFromCardAsync(AMASServiceReference.GetPhotoFromCardRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CommonServiceHeader
    {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPhotoFromIAMAS", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPhotoFromIAMASRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AMASServiceReference.CommonServiceHeader CommonServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SERIYA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string FIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string SAA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string s;
        
        public GetPhotoFromIAMASRequest()
        {
        }
        
        public GetPhotoFromIAMASRequest(AMASServiceReference.CommonServiceHeader CommonServiceHeader, string SERIYA, string FIN, string SAA, string s)
        {
            this.CommonServiceHeader = CommonServiceHeader;
            this.SERIYA = SERIYA;
            this.FIN = FIN;
            this.SAA = SAA;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPhotoFromIAMASResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPhotoFromIAMASResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetPhotoFromIAMASResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SAA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string s;
        
        public GetPhotoFromIAMASResponse()
        {
        }
        
        public GetPhotoFromIAMASResponse(byte[] GetPhotoFromIAMASResult, string SAA, string s)
        {
            this.GetPhotoFromIAMASResult = GetPhotoFromIAMASResult;
            this.SAA = SAA;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPhotoFromIAMAS24", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPhotoFromIAMAS24Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AMASServiceReference.CommonServiceHeader CommonServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SERIYA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string Number;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string FIN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string SAA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string s;
        
        public GetPhotoFromIAMAS24Request()
        {
        }
        
        public GetPhotoFromIAMAS24Request(AMASServiceReference.CommonServiceHeader CommonServiceHeader, string SERIYA, string Number, string FIN, string SAA, string s)
        {
            this.CommonServiceHeader = CommonServiceHeader;
            this.SERIYA = SERIYA;
            this.Number = Number;
            this.FIN = FIN;
            this.SAA = SAA;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPhotoFromIAMAS24Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPhotoFromIAMAS24Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetPhotoFromIAMAS24Result;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string SAA;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string s;
        
        public GetPhotoFromIAMAS24Response()
        {
        }
        
        public GetPhotoFromIAMAS24Response(byte[] GetPhotoFromIAMAS24Result, string SAA, string s)
        {
            this.GetPhotoFromIAMAS24Result = GetPhotoFromIAMAS24Result;
            this.SAA = SAA;
            this.s = s;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPhotoFromCard", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPhotoFromCardRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public AMASServiceReference.CommonServiceHeader CommonServiceHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string fin;
        
        public GetPhotoFromCardRequest()
        {
        }
        
        public GetPhotoFromCardRequest(AMASServiceReference.CommonServiceHeader CommonServiceHeader, string fin)
        {
            this.CommonServiceHeader = CommonServiceHeader;
            this.fin = fin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPhotoFromCardResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPhotoFromCardResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public AMASServiceReference.ArrayOfXElement GetPhotoFromCardResult;
        
        public GetPhotoFromCardResponse()
        {
        }
        
        public GetPhotoFromCardResponse(AMASServiceReference.ArrayOfXElement GetPhotoFromCardResult)
        {
            this.GetPhotoFromCardResult = GetPhotoFromCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface GetPhotoFromIAMASSoapChannel : AMASServiceReference.GetPhotoFromIAMASSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class GetPhotoFromIAMASSoapClient : System.ServiceModel.ClientBase<AMASServiceReference.GetPhotoFromIAMASSoap>, AMASServiceReference.GetPhotoFromIAMASSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GetPhotoFromIAMASSoapClient(CommonServiceHeader header, EndpointConfiguration endpointConfiguration) : 
                base(GetPhotoFromIAMASSoapClient.GetBindingForEndpoint(endpointConfiguration), GetPhotoFromIAMASSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetPhotoFromIAMASSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GetPhotoFromIAMASSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetPhotoFromIAMASSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GetPhotoFromIAMASSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GetPhotoFromIAMASSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AMASServiceReference.GetPhotoFromIAMASResponse> GetPhotoFromIAMASAsync(AMASServiceReference.GetPhotoFromIAMASRequest request)
        {
            return base.Channel.GetPhotoFromIAMASAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMASServiceReference.GetPhotoFromIAMAS24Response> GetPhotoFromIAMAS24Async(AMASServiceReference.GetPhotoFromIAMAS24Request request)
        {
            return base.Channel.GetPhotoFromIAMAS24Async(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AMASServiceReference.GetPhotoFromCardResponse> AMASServiceReference.GetPhotoFromIAMASSoap.GetPhotoFromCardAsync(AMASServiceReference.GetPhotoFromCardRequest request)
        {
            return base.Channel.GetPhotoFromCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<AMASServiceReference.GetPhotoFromCardResponse> GetPhotoFromCardAsync(AMASServiceReference.CommonServiceHeader CommonServiceHeader, string fin)
        {
            AMASServiceReference.GetPhotoFromCardRequest inValue = new AMASServiceReference.GetPhotoFromCardRequest();
            inValue.CommonServiceHeader = CommonServiceHeader;
            inValue.fin = fin;
            return ((AMASServiceReference.GetPhotoFromIAMASSoap)(this)).GetPhotoFromCardAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetPhotoFromIAMASSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.GetPhotoFromIAMASSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.GetPhotoFromIAMASSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.dim.gov.az/ws_amas_balans/getphotofromiamas.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.GetPhotoFromIAMASSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://ws.dim.gov.az/ws_amas_balans/getphotofromiamas.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            GetPhotoFromIAMASSoap,
            
            GetPhotoFromIAMASSoap12,
        }
    }
    
    [System.Xml.Serialization.XmlSchemaProviderAttribute(null, IsAny=true)]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil-lib", "2.2.0.0")]
    public partial class ArrayOfXElement : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Collections.Generic.List<System.Xml.Linq.XElement> nodesList = new System.Collections.Generic.List<System.Xml.Linq.XElement>();
        
        public ArrayOfXElement()
        {
        }
        
        public virtual System.Collections.Generic.List<System.Xml.Linq.XElement> Nodes
        {
            get
            {
                return this.nodesList;
            }
        }
        
        public virtual System.Xml.Schema.XmlSchema GetSchema()
        {
            throw new System.NotImplementedException();
        }
        
        public virtual void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Collections.Generic.IEnumerator<System.Xml.Linq.XElement> e = nodesList.GetEnumerator();
            for (
            ; e.MoveNext(); 
            )
            {
                ((System.Xml.Serialization.IXmlSerializable)(e.Current)).WriteXml(writer);
            }
        }
        
        public virtual void ReadXml(System.Xml.XmlReader reader)
        {
            for (
            ; (reader.NodeType != System.Xml.XmlNodeType.EndElement); 
            )
            {
                if ((reader.NodeType == System.Xml.XmlNodeType.Element))
                {
                    System.Xml.Linq.XElement elem = new System.Xml.Linq.XElement("default");
                    ((System.Xml.Serialization.IXmlSerializable)(elem)).ReadXml(reader);
                    Nodes.Add(elem);
                }
                else
                {
                    reader.Skip();
                }
            }
        }
    }
}
